openapi: 3.0.3
info:
  title: Library API
  version: 1.3.0
  description: STD22043
servers:
  - url: https://library.com
paths:
  /books:
    get:
      tags:
        - "Books"
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateRange
          description: Filter books by release date range
          required: false
          schema:
            type: object
        - $ref: "#/components/parameters/QueryPagination"
        - $ref: "#/components/parameters/PathPagination"
          properties:
            from:
              type: string
              format: date
              description: Start of date range
            to:
              type: string
              format: date
              description: End of date range
        - in: query
          name: page
          description: |
            The page number.
            Used when paginating the books
          schema:
            type: integer
            default: 1
          required: false
        - in: query
          name: pageSize
          description: |
            The count of all books in each page
          schema:
            type: integer
            default: 50
          required: false
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    put:
      tags:
        - "Books"
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Book"
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - "Books"
      summary: Attach an Author to a Book
      operationId: attachAuthorToBook
      parameters:
        - in: path
          name: bookId
          description: ID of the Book
          required: true
          schema:
            type: string
        - in: path
          name: authorId
          description: ID of the Author
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/authors:
    put:
      tags:
        - "Books"
      summary: Attach Authors to Books
      operationId: attachAuthorsToBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UpdateBookAuthor"
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/import:
    post:
      tags:
        - "Books"
      summary: Import books from Excel or JSON
      operationId: importBooks
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                excelFile:
                  type: string
                  format: binary
                  description: Excel file containing book data
                jsonFile:
                  type: string
                  format: binary
                  description: JSON file containing book data
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ImportBook"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: # Type MIME pour les fichiers Excel
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ImportBook"
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/borrowed:
    get:
      tags:
        - "Books"
      summary: Get a list of borrowed books
      operationId: getBorrowedBooks
      parameters:
        - in: query
          name: isBorrowed
          description: Filter books by borrowed status (true)
          required: false
          schema:
            type: boolean
            default: true
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/available:
    get:
      tags:
        - "Books"
      summary: Get a list of available books
      operationId: getAvailableBooks
      parameters:
        - in: query
          name: isBorrowed
          description: Filter books by borrowed status (false)
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /authors:
    get:
      tags:
        - "Authors"
      summary: Get all authors
      description: Retrieve a list of all authors or filter by name.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/QueryPagination"
        - $ref: "#/components/parameters/PathPagination"

      responses:
        200:
          $ref: "#/components/responses/AuthorList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    put:
      tags:
        - "Authors"
      summary: Create or update a list of authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
      responses:
        200:
          $ref: "#/components/responses/AuthorList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    delete:
      tags:
        - "Authors"
      summary: Delete an author by ID
      operationId: deleteAuthor
      parameters:
        - in: path
          name: authorId
          description: ID of the author to delete
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /authors/import:
    post:
      tags:
        - "Authors"
      summary: Import authors from Excel or JSON
      operationId: importAuthors
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                excelFile:
                  type: string
                  format: binary
                  description: Excel file containing author data
                jsonFile:
                  type: string
                  format: binary
                  description: JSON file containing author data
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: # Type MIME pour les fichiers Excel
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
      responses:
        200:
          $ref: "#/components/responses/AuthorList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /visitors:
    get:
      tags:
        - "Visitors"
      summary: Get a list of all visitors
      operationId: getAllVisitors
      responses:
        200:
          description: List of all visitors retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Visitor"
    post:
      tags:
        - "Visitors"
      summary: Create a new visitor
      operationId: createVisitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Visitor"
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /visitors/{visitorId}:
    delete:
      tags:
        - "Visitors"
      summary: Delete visitor by ID
      operationId: deleteVisitorById
      parameters:
        - in: path
          name: visitorId
          description: ID of the visitor to delete
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /actions/borrow:
    get:
      tags:
        - "Actions"
      summary: Get a list of all borrowed books
      operationId: getBorrowedBooks
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - "Actions"
      summary: Borrow a book
      operationId: borrowBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BorrowAction"
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /actions/borrow/{actionId}:
    delete:
      tags:
        - "Actions"
      summary: Delete an action record by ID
      operationId: deleteActionRecord
      parameters:
        - in: path
          name: actionId
          description: ID of the action record to delete
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /actions/return:
    get:
      tags:
        - "Actions"
      summary: Get a list of all returned books
      operationId: getReturnedBooks
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - "Actions"
      summary: Return a book
      operationId: returnBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReturnAction"
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /actions/return/{actionId}:
    delete:
      tags:
        - "Actions"
      summary: Delete a return action record by ID
      operationId: deleteReturnActionRecord
      parameters:
        - in: path
          name: actionId
          description: ID of the return action record to delete
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/BookList_200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
components:
  schemas:
    Book:
      type: object
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
        - type: object
          properties:
            file_type:
              enum:
                - Excel
                - JSON
            isBorrowed:
              type: boolean
      properties:
        author:
          $ref: "#/components/schemas/Author"
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
    ImportBook:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: string
    Visitor:
      type: object
      properties:
        IdAuthor:
          type: integer
        name:
          type: string
        reference:
          type: string
    BorrowAction:
      type: object
      properties:
        bookId:
          type: string
        visitorId:
          type: string
        timestamp:
          type: string
          format: date-time
    ReturnAction:
      type: object
      properties:
        bookId:
          type: string
        visitorId:
          type: string
        timestamp:
          type: string
          format: date-time
    Responsestatus:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: OK
    ResponsebodyTemplate:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Responsestatus"
        body:
          type: object
    BadRequestBody:
      allOf:
        - $ref: "#/components/schemas/ResponsebodyTemplate"
      example:
        status:
          code: 400
          message: Bad request
        body: {}
    Forbidden:
      allOf:
        - $ref: "#/components/schemas/ResponsebodyTemplate"
      example:
        status:
          code: 403
          message: Forbidden
        body: {}
    EternalServerError:
      allOf:
        - $ref: "#/components/schemas/ResponsebodyTemplate"
      example:
        status:
          code: 500
          message: Eternal server Error
        body: {}
    BookListBody:
      allOf:
        - $ref: "#/components/schemas/ResponsebodyTemplate"
        - properties:
            body:
              type: array
              items:
                $ref: "#/components/schemas/Book"
    AuthorListBody:
      allOf:
        - $ref: "#/components/schemas/ResponsebodyTemplate"
        - properties:
            body:
              type: array
              items:
                $ref: "#/components/schemas/Author"
  responses:
    BookList_200:
      description: List of book
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BookListBody"
    AuthorList_200:
      description: list of author
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthorListBody"
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestBody"
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Forbidden"
    500:
      description: Eternal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/EternalServerError"
  parameters:
    QueryPagination:
      in: query
      name: queryPagination
      description: "Page number for pagination"
      required: false
      schema:
        type: integer
        default: 1
    PathPagination:
      name: pathPagination
      in: query
      description: Page number for pagination
      required: true
      schema:
        type: integer
